### PR TITLE
add support for gdal.Open-able vfs paths

### PR DESCRIPTION
**Pull request by chapmanjacobd**

### CODE REVIEW

**Comment by jdalrym2** [comment]
Thanks for the contribution! I'd like one more thing before merge, and that'd be two unit tests (one for raster, the other for dataset) where the dataset is loaded into `/vsimem` and then we verify that no error is thrown and everything works as expected.

- [ ] Success unit test for `vsimem` objects.

**Comment by chapmanjacobd** [comment]
yes, I originally went for that but vsimem objects are not openable with gdal.Open

This is the simplest test that guarantees gdal.Open will get the path it needs for vsi paths that are gdal.Openable

**Comment by jdalrym2** [comment]
Right. Is there an (easy) way to open up the test raster and test dataset files and copy them to `/vsimem`? I'm comfortable with writing rasters and datasets in GDAL so worst case I can add the code to read in the files, write out to `/vsimem`, and test.

**Comment by jdalrym2** [comment]
I'll dive deeper. You may be right that this is sufficient.

**Comment by chapmanjacobd** [comment]
maybe vsitar or vsizip could work. I am using this with vsigs and it works

**Comment by jdalrym2** [comment]
Closing in support of https://github.com/jdalrym2/exactextract/pull/5

**Pull request closed without merging**
